// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.sidekick.news' | (string & {});
};

/**
 * AgentConfig
 *
 * Runtime configuration for a named agent — model and prompt definitions.
 *
 * A row must exist before an agent can be invoked. There are no code-level
 * defaults; agents raise KeyError if no row is found.
 *
 * agent_id examples:
 * "ingestion-worker"
 * "processor:summary"
 * "beat-agent:city-council:springfield-il"
 * "editor-agent"
 *
 * prompts keys are agent-specific slot names, e.g.:
 * {"system": "...", "analyze_template": "..."}
 */
export type AgentConfig = {
    /**
     * Id
     */
    id: string;
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Model
     */
    model: string;
    /**
     * Prompts
     */
    prompts: {
        [key: string]: string;
    };
    /**
     * Skills
     */
    skills?: Array<string>;
    /**
     * Updated At
     */
    updated_at?: string;
    /**
     * Updated By
     */
    updated_by?: string | null;
};

/**
 * AgentConfigCreate
 */
export type AgentConfigCreate = {
    /**
     * Id
     */
    id?: string | null;
    /**
     * Agent Id
     */
    agent_id?: string | null;
    /**
     * Model
     */
    model: string;
    /**
     * Prompts
     */
    prompts: {
        [key: string]: string;
    };
    /**
     * Skills
     */
    skills?: Array<string>;
    /**
     * Updated By
     */
    updated_by?: string | null;
};

/**
 * ApiClient
 *
 * Machine API client credentials and authorization metadata.
 */
export type ApiClient = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Key Prefix
     */
    key_prefix: string;
    /**
     * Key Hash
     */
    key_hash: string;
    /**
     * Roles
     */
    roles?: Array<string>;
    /**
     * Scopes
     */
    scopes?: Array<string>;
    /**
     * Status
     */
    status?: string;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Last Used At
     */
    last_used_at?: string | null;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Rotated From
     */
    rotated_from?: string | null;
};

/**
 * ApiClientCreate
 */
export type ApiClientCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Roles
     */
    roles: Array<string>;
    /**
     * Scopes
     */
    scopes?: Array<string>;
    /**
     * Expires At
     */
    expires_at?: string | null;
};

/**
 * ApiClientRotate
 */
export type ApiClientRotate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Roles
     */
    roles?: Array<string> | null;
    /**
     * Scopes
     */
    scopes?: Array<string> | null;
    /**
     * Expires At
     */
    expires_at?: string | null;
};

/**
 * ApiKeyIssuedResponse
 */
export type ApiKeyIssuedResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Key Prefix
     */
    key_prefix: string;
    /**
     * Plaintext Key
     */
    plaintext_key: string;
    /**
     * Roles
     */
    roles: Array<string>;
    /**
     * Scopes
     */
    scopes: Array<string>;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expires At
     */
    expires_at?: string | null;
};

/**
 * Artifact
 *
 * A unit of content at any pipeline stage — raw, processed, analysis, connections, or draft.
 */
export type Artifact = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    content_type: ContentType;
    stage: Stage;
    /**
     * Media Type
     */
    media_type?: string | null;
    processing_profile?: ProcessingProfile | null;
    /**
     * Derived From
     */
    derived_from?: Array<string> | null;
    /**
     * Source Id
     */
    source_id?: string | null;
    /**
     * Event Group
     */
    event_group?: string | null;
    /**
     * Beat
     */
    beat?: string | null;
    /**
     * Geo
     */
    geo?: string | null;
    /**
     * Period Start
     */
    period_start?: string | null;
    /**
     * Period End
     */
    period_end?: string | null;
    /**
     * Assignment Id
     */
    assignment_id?: string | null;
    /**
     * Entities
     */
    entities?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Topics
     */
    topics?: Array<string> | null;
    /**
     * Embedding
     */
    embedding?: Array<number> | null;
    /**
     * Content Uri
     */
    content_uri?: string | null;
    /**
     * Acquisition Url
     */
    acquisition_url?: string | null;
    /**
     * Created By
     */
    created_by?: string | null;
    /**
     * Created At
     */
    created_at?: string;
    status?: ArtifactStatus;
    /**
     * Superseded By
     */
    superseded_by?: string | null;
};

/**
 * ArtifactPatch
 */
export type ArtifactPatch = {
    /**
     * Media Type
     */
    media_type?: string | null;
    /**
     * Event Group
     */
    event_group?: string | null;
    /**
     * Beat
     */
    beat?: string | null;
    /**
     * Geo
     */
    geo?: string | null;
    /**
     * Period Start
     */
    period_start?: string | null;
    /**
     * Period End
     */
    period_end?: string | null;
    /**
     * Assignment Id
     */
    assignment_id?: string | null;
    /**
     * Entities
     */
    entities?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Topics
     */
    topics?: Array<string> | null;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Superseded By
     */
    superseded_by?: string | null;
};

/**
 * ArtifactStatus
 */
export type ArtifactStatus = 'active' | 'pending_acquisition' | 'superseded' | 'retracted';

/**
 * Assignment
 *
 * A targeted investigation request — research, story, or monitor type.
 */
export type Assignment = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Query Text
     */
    query_text: string;
    /**
     * Query Params
     */
    query_params?: {
        [key: string]: unknown;
    } | null;
    /**
     * Triggered By
     */
    triggered_by?: string | null;
    /**
     * Triggered By Id
     */
    triggered_by_id?: string | null;
    /**
     * Triggered At
     */
    triggered_at?: string;
    /**
     * Parent Assignment
     */
    parent_assignment?: string | null;
    /**
     * Artifacts In
     */
    artifacts_in?: Array<string> | null;
    /**
     * Artifacts Out
     */
    artifacts_out?: Array<string> | null;
    /**
     * Sub Assignments
     */
    sub_assignments?: Array<string> | null;
    /**
     * Monitor
     */
    monitor?: {
        [key: string]: unknown;
    } | null;
};

/**
 * AssignmentCreate
 */
export type AssignmentCreate = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Query Text
     */
    query_text: string;
    /**
     * Query Params
     */
    query_params?: {
        [key: string]: unknown;
    } | null;
    /**
     * Triggered By
     */
    triggered_by?: string | null;
    /**
     * Triggered By Id
     */
    triggered_by_id?: string | null;
    /**
     * Triggered At
     */
    triggered_at?: string | null;
    /**
     * Parent Assignment
     */
    parent_assignment?: string | null;
    /**
     * Artifacts In
     */
    artifacts_in?: Array<string> | null;
    /**
     * Artifacts Out
     */
    artifacts_out?: Array<string> | null;
    /**
     * Sub Assignments
     */
    sub_assignments?: Array<string> | null;
    /**
     * Monitor
     */
    monitor?: {
        [key: string]: unknown;
    } | null;
};

/**
 * AssignmentPatch
 */
export type AssignmentPatch = {
    /**
     * Type
     */
    type?: string | null;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Query Text
     */
    query_text?: string | null;
    /**
     * Query Params
     */
    query_params?: {
        [key: string]: unknown;
    } | null;
    /**
     * Triggered By
     */
    triggered_by?: string | null;
    /**
     * Triggered By Id
     */
    triggered_by_id?: string | null;
    /**
     * Triggered At
     */
    triggered_at?: string | null;
    /**
     * Parent Assignment
     */
    parent_assignment?: string | null;
    /**
     * Artifacts In
     */
    artifacts_in?: Array<string> | null;
    /**
     * Artifacts Out
     */
    artifacts_out?: Array<string> | null;
    /**
     * Sub Assignments
     */
    sub_assignments?: Array<string> | null;
    /**
     * Monitor
     */
    monitor?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ContentType
 */
export type ContentType = 'document-raw' | 'audio-raw' | 'video-raw' | 'document-text' | 'entity-extract' | 'structured-data' | 'summary' | 'beat-brief' | 'trend-note' | 'budget-comparison' | 'policy-diff' | 'flag' | 'connection-memo' | 'cross-beat-flag' | 'story-draft';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ProcessingProfile
 *
 * Downstream processing intent set at ingest time (spider or source default).
 *
 * Describes what the pipeline should produce after normalization.
 */
export type ProcessingProfile = 'full' | 'structured' | 'index' | 'evidence';

/**
 * Source
 *
 * A recurring information channel (e.g. a council agenda page, an RSS feed).
 */
export type Source = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Endpoint
     */
    endpoint?: string | null;
    /**
     * Schedule
     */
    schedule?: {
        [key: string]: unknown;
    } | null;
    /**
     * Beat
     */
    beat?: string | null;
    /**
     * Geo
     */
    geo?: string | null;
    /**
     * Related Sources
     */
    related_sources?: Array<string> | null;
    /**
     * Registered At
     */
    registered_at?: string | null;
    /**
     * Health
     */
    health?: {
        [key: string]: unknown;
    } | null;
    source_tier?: SourceTier;
    /**
     * Outlet
     */
    outlet?: string | null;
    status?: SourceStatus;
};

/**
 * SourceCreate
 */
export type SourceCreate = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Endpoint
     */
    endpoint?: string | null;
    /**
     * Schedule
     */
    schedule?: {
        [key: string]: unknown;
    } | null;
    /**
     * Beat
     */
    beat?: string | null;
    /**
     * Geo
     */
    geo?: string | null;
    /**
     * Related Sources
     */
    related_sources?: Array<string> | null;
    /**
     * Registered At
     */
    registered_at?: string | null;
    /**
     * Health
     */
    health?: {
        [key: string]: unknown;
    } | null;
    /**
     * Source Tier
     */
    source_tier?: string | null;
    /**
     * Outlet
     */
    outlet?: string | null;
    status?: SourceStatus;
};

/**
 * SourcePatch
 */
export type SourcePatch = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Endpoint
     */
    endpoint?: string | null;
    /**
     * Schedule
     */
    schedule?: {
        [key: string]: unknown;
    } | null;
    /**
     * Beat
     */
    beat?: string | null;
    /**
     * Geo
     */
    geo?: string | null;
    /**
     * Related Sources
     */
    related_sources?: Array<string> | null;
    /**
     * Registered At
     */
    registered_at?: string | null;
    /**
     * Health
     */
    health?: {
        [key: string]: unknown;
    } | null;
    /**
     * Source Tier
     */
    source_tier?: string | null;
    /**
     * Outlet
     */
    outlet?: string | null;
    status?: SourceStatus | null;
};

/**
 * SourceStatus
 *
 * Lifecycle flag for scheduled ingestion — inactive sources are skipped by list-due.
 */
export type SourceStatus = 'active' | 'inactive';

/**
 * SourceTier
 *
 * Whether a source is the issuing organization or a secondary reporter.
 *
 * PRIMARY: The originating organization itself — government portals, agency
 * releases, court filings, official video streams. Default.
 * SECONDARY: Another newsroom or analyst reporting on primary events —
 * newspapers, wire services, think tanks. Requires ``outlet`` to be set
 * on the Source row.
 */
export type SourceTier = 'primary' | 'secondary';

/**
 * Stage
 */
export type Stage = 'raw' | 'processed' | 'analysis' | 'connections' | 'draft';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListSourcesSourcesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sources';
};

export type ListSourcesSourcesGetResponses = {
    /**
     * Response List Sources Sources Get
     *
     * Successful Response
     */
    200: Array<Source>;
};

export type ListSourcesSourcesGetResponse = ListSourcesSourcesGetResponses[keyof ListSourcesSourcesGetResponses];

export type CreateSourceSourcesPostData = {
    body: SourceCreate;
    path?: never;
    query?: never;
    url: '/sources';
};

export type CreateSourceSourcesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSourceSourcesPostError = CreateSourceSourcesPostErrors[keyof CreateSourceSourcesPostErrors];

export type CreateSourceSourcesPostResponses = {
    /**
     * Successful Response
     */
    200: Source;
};

export type CreateSourceSourcesPostResponse = CreateSourceSourcesPostResponses[keyof CreateSourceSourcesPostResponses];

export type DeleteSourceSourcesSourceIdDeleteData = {
    body?: never;
    path: {
        /**
         * Source Id
         */
        source_id: string;
    };
    query?: never;
    url: '/sources/{source_id}';
};

export type DeleteSourceSourcesSourceIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSourceSourcesSourceIdDeleteError = DeleteSourceSourcesSourceIdDeleteErrors[keyof DeleteSourceSourcesSourceIdDeleteErrors];

export type DeleteSourceSourcesSourceIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteSourceSourcesSourceIdDeleteResponse = DeleteSourceSourcesSourceIdDeleteResponses[keyof DeleteSourceSourcesSourceIdDeleteResponses];

export type GetSourceSourcesSourceIdGetData = {
    body?: never;
    path: {
        /**
         * Source Id
         */
        source_id: string;
    };
    query?: never;
    url: '/sources/{source_id}';
};

export type GetSourceSourcesSourceIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSourceSourcesSourceIdGetError = GetSourceSourcesSourceIdGetErrors[keyof GetSourceSourcesSourceIdGetErrors];

export type GetSourceSourcesSourceIdGetResponses = {
    /**
     * Successful Response
     */
    200: Source;
};

export type GetSourceSourcesSourceIdGetResponse = GetSourceSourcesSourceIdGetResponses[keyof GetSourceSourcesSourceIdGetResponses];

export type PatchSourceSourcesSourceIdPatchData = {
    body: SourcePatch;
    path: {
        /**
         * Source Id
         */
        source_id: string;
    };
    query?: never;
    url: '/sources/{source_id}';
};

export type PatchSourceSourcesSourceIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchSourceSourcesSourceIdPatchError = PatchSourceSourcesSourceIdPatchErrors[keyof PatchSourceSourcesSourceIdPatchErrors];

export type PatchSourceSourcesSourceIdPatchResponses = {
    /**
     * Successful Response
     */
    200: Source;
};

export type PatchSourceSourcesSourceIdPatchResponse = PatchSourceSourcesSourceIdPatchResponses[keyof PatchSourceSourcesSourceIdPatchResponses];

export type ListAssignmentsAssignmentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/assignments';
};

export type ListAssignmentsAssignmentsGetResponses = {
    /**
     * Response List Assignments Assignments Get
     *
     * Successful Response
     */
    200: Array<Assignment>;
};

export type ListAssignmentsAssignmentsGetResponse = ListAssignmentsAssignmentsGetResponses[keyof ListAssignmentsAssignmentsGetResponses];

export type CreateAssignmentAssignmentsPostData = {
    body: AssignmentCreate;
    path?: never;
    query?: never;
    url: '/assignments';
};

export type CreateAssignmentAssignmentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAssignmentAssignmentsPostError = CreateAssignmentAssignmentsPostErrors[keyof CreateAssignmentAssignmentsPostErrors];

export type CreateAssignmentAssignmentsPostResponses = {
    /**
     * Successful Response
     */
    200: Assignment;
};

export type CreateAssignmentAssignmentsPostResponse = CreateAssignmentAssignmentsPostResponses[keyof CreateAssignmentAssignmentsPostResponses];

export type DeleteAssignmentAssignmentsAssignmentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Assignment Id
         */
        assignment_id: string;
    };
    query?: never;
    url: '/assignments/{assignment_id}';
};

export type DeleteAssignmentAssignmentsAssignmentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAssignmentAssignmentsAssignmentIdDeleteError = DeleteAssignmentAssignmentsAssignmentIdDeleteErrors[keyof DeleteAssignmentAssignmentsAssignmentIdDeleteErrors];

export type DeleteAssignmentAssignmentsAssignmentIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAssignmentAssignmentsAssignmentIdDeleteResponse = DeleteAssignmentAssignmentsAssignmentIdDeleteResponses[keyof DeleteAssignmentAssignmentsAssignmentIdDeleteResponses];

export type GetAssignmentAssignmentsAssignmentIdGetData = {
    body?: never;
    path: {
        /**
         * Assignment Id
         */
        assignment_id: string;
    };
    query?: never;
    url: '/assignments/{assignment_id}';
};

export type GetAssignmentAssignmentsAssignmentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAssignmentAssignmentsAssignmentIdGetError = GetAssignmentAssignmentsAssignmentIdGetErrors[keyof GetAssignmentAssignmentsAssignmentIdGetErrors];

export type GetAssignmentAssignmentsAssignmentIdGetResponses = {
    /**
     * Successful Response
     */
    200: Assignment;
};

export type GetAssignmentAssignmentsAssignmentIdGetResponse = GetAssignmentAssignmentsAssignmentIdGetResponses[keyof GetAssignmentAssignmentsAssignmentIdGetResponses];

export type PatchAssignmentAssignmentsAssignmentIdPatchData = {
    body: AssignmentPatch;
    path: {
        /**
         * Assignment Id
         */
        assignment_id: string;
    };
    query?: never;
    url: '/assignments/{assignment_id}';
};

export type PatchAssignmentAssignmentsAssignmentIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchAssignmentAssignmentsAssignmentIdPatchError = PatchAssignmentAssignmentsAssignmentIdPatchErrors[keyof PatchAssignmentAssignmentsAssignmentIdPatchErrors];

export type PatchAssignmentAssignmentsAssignmentIdPatchResponses = {
    /**
     * Successful Response
     */
    200: Assignment;
};

export type PatchAssignmentAssignmentsAssignmentIdPatchResponse = PatchAssignmentAssignmentsAssignmentIdPatchResponses[keyof PatchAssignmentAssignmentsAssignmentIdPatchResponses];

export type ListAgentConfigsAgentConfigsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agent-configs';
};

export type ListAgentConfigsAgentConfigsGetResponses = {
    /**
     * Response List Agent Configs Agent Configs Get
     *
     * Successful Response
     */
    200: Array<AgentConfig>;
};

export type ListAgentConfigsAgentConfigsGetResponse = ListAgentConfigsAgentConfigsGetResponses[keyof ListAgentConfigsAgentConfigsGetResponses];

export type CreateAgentConfigAgentConfigsPostData = {
    body: AgentConfigCreate;
    path?: never;
    query?: never;
    url: '/agent-configs';
};

export type CreateAgentConfigAgentConfigsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAgentConfigAgentConfigsPostError = CreateAgentConfigAgentConfigsPostErrors[keyof CreateAgentConfigAgentConfigsPostErrors];

export type CreateAgentConfigAgentConfigsPostResponses = {
    /**
     * Successful Response
     */
    200: AgentConfig;
};

export type CreateAgentConfigAgentConfigsPostResponse = CreateAgentConfigAgentConfigsPostResponses[keyof CreateAgentConfigAgentConfigsPostResponses];

export type DeleteAgentConfigAgentConfigsAgentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agent-configs/{agent_id}';
};

export type DeleteAgentConfigAgentConfigsAgentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAgentConfigAgentConfigsAgentIdDeleteError = DeleteAgentConfigAgentConfigsAgentIdDeleteErrors[keyof DeleteAgentConfigAgentConfigsAgentIdDeleteErrors];

export type DeleteAgentConfigAgentConfigsAgentIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAgentConfigAgentConfigsAgentIdDeleteResponse = DeleteAgentConfigAgentConfigsAgentIdDeleteResponses[keyof DeleteAgentConfigAgentConfigsAgentIdDeleteResponses];

export type GetAgentConfigAgentConfigsAgentIdGetData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agent-configs/{agent_id}';
};

export type GetAgentConfigAgentConfigsAgentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAgentConfigAgentConfigsAgentIdGetError = GetAgentConfigAgentConfigsAgentIdGetErrors[keyof GetAgentConfigAgentConfigsAgentIdGetErrors];

export type GetAgentConfigAgentConfigsAgentIdGetResponses = {
    /**
     * Successful Response
     */
    200: AgentConfig;
};

export type GetAgentConfigAgentConfigsAgentIdGetResponse = GetAgentConfigAgentConfigsAgentIdGetResponses[keyof GetAgentConfigAgentConfigsAgentIdGetResponses];

export type PutAgentConfigAgentConfigsAgentIdPutData = {
    body: AgentConfigCreate;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agent-configs/{agent_id}';
};

export type PutAgentConfigAgentConfigsAgentIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutAgentConfigAgentConfigsAgentIdPutError = PutAgentConfigAgentConfigsAgentIdPutErrors[keyof PutAgentConfigAgentConfigsAgentIdPutErrors];

export type PutAgentConfigAgentConfigsAgentIdPutResponses = {
    /**
     * Successful Response
     */
    200: AgentConfig;
};

export type PutAgentConfigAgentConfigsAgentIdPutResponse = PutAgentConfigAgentConfigsAgentIdPutResponses[keyof PutAgentConfigAgentConfigsAgentIdPutResponses];

export type ListArtifactsArtifactsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/artifacts';
};

export type ListArtifactsArtifactsGetResponses = {
    /**
     * Response List Artifacts Artifacts Get
     *
     * Successful Response
     */
    200: Array<Artifact>;
};

export type ListArtifactsArtifactsGetResponse = ListArtifactsArtifactsGetResponses[keyof ListArtifactsArtifactsGetResponses];

export type RetractArtifactArtifactsArtifactIdDeleteData = {
    body?: never;
    path: {
        /**
         * Artifact Id
         */
        artifact_id: string;
    };
    query?: never;
    url: '/artifacts/{artifact_id}';
};

export type RetractArtifactArtifactsArtifactIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetractArtifactArtifactsArtifactIdDeleteError = RetractArtifactArtifactsArtifactIdDeleteErrors[keyof RetractArtifactArtifactsArtifactIdDeleteErrors];

export type RetractArtifactArtifactsArtifactIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RetractArtifactArtifactsArtifactIdDeleteResponse = RetractArtifactArtifactsArtifactIdDeleteResponses[keyof RetractArtifactArtifactsArtifactIdDeleteResponses];

export type GetArtifactArtifactsArtifactIdGetData = {
    body?: never;
    path: {
        /**
         * Artifact Id
         */
        artifact_id: string;
    };
    query?: never;
    url: '/artifacts/{artifact_id}';
};

export type GetArtifactArtifactsArtifactIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetArtifactArtifactsArtifactIdGetError = GetArtifactArtifactsArtifactIdGetErrors[keyof GetArtifactArtifactsArtifactIdGetErrors];

export type GetArtifactArtifactsArtifactIdGetResponses = {
    /**
     * Successful Response
     */
    200: Artifact;
};

export type GetArtifactArtifactsArtifactIdGetResponse = GetArtifactArtifactsArtifactIdGetResponses[keyof GetArtifactArtifactsArtifactIdGetResponses];

export type PatchArtifactArtifactsArtifactIdPatchData = {
    body: ArtifactPatch;
    path: {
        /**
         * Artifact Id
         */
        artifact_id: string;
    };
    query?: never;
    url: '/artifacts/{artifact_id}';
};

export type PatchArtifactArtifactsArtifactIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchArtifactArtifactsArtifactIdPatchError = PatchArtifactArtifactsArtifactIdPatchErrors[keyof PatchArtifactArtifactsArtifactIdPatchErrors];

export type PatchArtifactArtifactsArtifactIdPatchResponses = {
    /**
     * Successful Response
     */
    200: Artifact;
};

export type PatchArtifactArtifactsArtifactIdPatchResponse = PatchArtifactArtifactsArtifactIdPatchResponses[keyof PatchArtifactArtifactsArtifactIdPatchResponses];

export type ListApiClientsApiClientsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api-clients';
};

export type ListApiClientsApiClientsGetResponses = {
    /**
     * Response List Api Clients Api Clients Get
     *
     * Successful Response
     */
    200: Array<ApiClient>;
};

export type ListApiClientsApiClientsGetResponse = ListApiClientsApiClientsGetResponses[keyof ListApiClientsApiClientsGetResponses];

export type CreateApiClientApiClientsPostData = {
    body: ApiClientCreate;
    path?: never;
    query?: never;
    url: '/api-clients';
};

export type CreateApiClientApiClientsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateApiClientApiClientsPostError = CreateApiClientApiClientsPostErrors[keyof CreateApiClientApiClientsPostErrors];

export type CreateApiClientApiClientsPostResponses = {
    /**
     * Successful Response
     */
    200: ApiKeyIssuedResponse;
};

export type CreateApiClientApiClientsPostResponse = CreateApiClientApiClientsPostResponses[keyof CreateApiClientApiClientsPostResponses];

export type RotateApiClientKeyApiClientsClientIdRotatePostData = {
    body: ApiClientRotate;
    path: {
        /**
         * Client Id
         */
        client_id: string;
    };
    query?: never;
    url: '/api-clients/{client_id}/rotate';
};

export type RotateApiClientKeyApiClientsClientIdRotatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RotateApiClientKeyApiClientsClientIdRotatePostError = RotateApiClientKeyApiClientsClientIdRotatePostErrors[keyof RotateApiClientKeyApiClientsClientIdRotatePostErrors];

export type RotateApiClientKeyApiClientsClientIdRotatePostResponses = {
    /**
     * Successful Response
     */
    200: ApiKeyIssuedResponse;
};

export type RotateApiClientKeyApiClientsClientIdRotatePostResponse = RotateApiClientKeyApiClientsClientIdRotatePostResponses[keyof RotateApiClientKeyApiClientsClientIdRotatePostResponses];

export type RevokeApiClientApiClientsClientIdRevokePostData = {
    body?: never;
    path: {
        /**
         * Client Id
         */
        client_id: string;
    };
    query?: never;
    url: '/api-clients/{client_id}/revoke';
};

export type RevokeApiClientApiClientsClientIdRevokePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeApiClientApiClientsClientIdRevokePostError = RevokeApiClientApiClientsClientIdRevokePostErrors[keyof RevokeApiClientApiClientsClientIdRevokePostErrors];

export type RevokeApiClientApiClientsClientIdRevokePostResponses = {
    /**
     * Successful Response
     */
    200: ApiClient;
};

export type RevokeApiClientApiClientsClientIdRevokePostResponse = RevokeApiClientApiClientsClientIdRevokePostResponses[keyof RevokeApiClientApiClientsClientIdRevokePostResponses];
